### ISSUE TITLE
Problème d'installation

### ISSUE THREAD

**Issue by geobrun** [naturalsolutions/geocam#8]
Bonjour,

J'essaye d'installer GeoCam sur un serveur Debian 11. Je ne suis pas familier de Docker, il doit y avoir quelque chose que je n'ai pas compris.

Voici ce que j'ai fait jusqu'à présent : 
- récupéré la version dev de GeoCam présent sur le dépôt
- installé `docker` via : `sudo apt install docker`
- installé la dernière version de `docker-compose` via : `sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`, puis `sudo chmod +x /usr/local/bin/docker-compose`
- modifié légèrement le fichier `docker/.env`, puis exécuté la commande `./scripts/docker.sh up -d` comme indiqué dans la documentation

Lors de l'exécution de ce dernier script, une seule erreur apparaît :
```
✔ Network geonature-annotation_annotation_nw  Created                                                                       0.3s 
 ✔ Network geonature-annotation_default        Created                                                                       0.2s 
 ✔ Volume "geonature-annotation_db_data"       Created                                                                       0.1s 
 ✔ Volume "geonature-annotation_minio_data"    Created                                                                       0.0s 
 ✔ Container geonature-annotation-keycloak-1   Started                                                                       7.2s 
 ✔ Container geonature-annotation-minio-1      Healthy                                                                      38.2s 
 ✔ Container geonature-annotation-db-1         Healthy                                                                      27.7s 
 ✔ Container geonature-annotation-doc-1        Started                                                                       7.2s 
 ✔ Container geonature-annotation-api-1        Healthy                                                                      60.3s 
 ✘ Container geonature-annotation-frontend-1   Error                                                                        69.5s 
 ✔ Container geonature-annotation-traefik-1    Created 
```

@mvergez, as-tu une piste pour m'aiguiller s'il te plaît ? Peut-être ai-je oublié d'installer quelque chose ou peut-être que je n'ai pas renseigné correctement un paramètre dans le fichier `docker/.env` ?

**Comment by mvergez** [comment]
Bonjour @geobrun !
Super que tu ais tenté d'installer GeoCam !
Alors, l'erreur montre qu'il y a un souci avec le frontend. 
Pour voir ce qu'il se passe, peux-tu m'envoyer le retour de la commande suivante : `./scripts/docker.sh logs frontend`. Cela permet de voir les logs du conteneur frontend et donc de voir s'il y a des erreurs.
Merci !

**Comment by geobrun** [comment]
Ok, merci ! J'ai seulement ces lignes qui apparaissent des dizaines de fois :
```
geonature-annotation-frontend-1  | > frontend@0.1.0 start
geonature-annotation-frontend-1  | > react-scripts start
geonature-annotation-frontend-1  | sh: react-scripts: not found

```

**Comment by mvergez** [comment]
Ah oui ! Il faudrait qu'on le change ça... Les paquets npm (dépendances) ne sont pas installés à la première "installation". Et donc le front ne peux pas démarrer

Il faudrait que tu lances : `./scripts/docker.sh run frontend npm install`. 
Cela permet d'exécuter la commande d'installation des paquets (`npm install`) dans un conteneur frontend. Cela va installer les paquets npm du front dans le conteneur mais tu verras aussi apparaitre le dossier `nodes_modules` dans le repertoire de GeoCam sur ta machine, c'est normal car les fichiers et dossiers sont partagés entre ta machine et le conteneur.

Il faudra qu'on mette à jour le code et/ou la documentation.

J'espère que cela va fonctionner !

**Comment by geobrun** [comment]
Ok, c'est bon, ça a fonctionné, j'ai bien accès au frontend ! Par contre, je rencontre quelques bugs.

Je n'arrive pas à ajouter un projet. Au moment d'enregistrer le nouveau projet, je clique sur "Enregistrer" mais il ne se passe rien. Voilà les retours que j'ai dans Firefox : 
- Des messages dans ce genre : `Warning: validateDOMNesting(...): <h6> cannot appear as a child of <h2>.h6withEmotionCache/<@http://localhost:8889/static/js/bundle.js:18545:66Typography@http://localhost:8889/static/js/bundle.js:50093:87h2`
- La requête `POST http://192.168.*.*:8889/api/v1/projects/` renvoie `500 Internal Server Error`
- Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://192.168.*.*:8889/api/v1/projects/. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant. Code d’état : 500.

Je suppose que c'est parce que j'ai remplacé `localhost` dans le fichier `docker./env` par une adresse IP du type `192.168.*.*` ?

Pour la documentation, je peux m'en charger : je n'ai pas de grandes compétences en codage, mais pour écrire, ça devrait aller ! :)

**Comment by mvergez** [comment]
Super pour le frontend !

Effectivement, le fichier `.env` d'exemple est un `.env` de dev avec localhost. J'ai un exemple de fichier un peu plus de prod, mais qui est fait pour du https, à voir si ça marche pour toi. Je te mets ci-dessous les lignes à changer :
```
DOMAIN=192.168.*.*
MINIO_ENTRYPOINT_URL=http://${DOMAIN}
REACT_APP_API_PATH=http://${DOMAIN}/api/v1
TRAEFIK_ROUTER_RULE_API=HOST(`${DOMAIN}`) && PathPrefix(`${API_ROOT_PATH}`)
TRAEFIK_ROUTER_RULE_FRONTEND=HOST(`${DOMAIN}`) && PathPrefix(`/`)
```

Essaie avec ça, je croise les doigts pour que ça fonctionne !

Merci beaucoup pour la documentation, avec plaisir ! Après c'est de notre côté pour les soucis d'installation des paquets je pense. Pour pouvoir automatiquement les installer, etc. A voir...

**Comment by mvergez** [comment]
Pardon j'avais oublié de te dire dans mon précédent message : as-tu fait `./scripts/docker.sh up -d` pour qu'il recharge le .env ?

**Comment by geobrun** [comment]
Oui, dans le doute, j'avais relancé les deux commandes `./scripts/docker.sh run frontend npm install` et `./scripts/docker.sh up -d`.

**Comment by mvergez** [comment]
C'est étrange ce problème de CORS...
Je pense que la configuration que je t'ai donnée est trop "prod", parce qu'il n'y a plus les ports. Tu n'as rien sur le port 80 (port http) de ta machine ? 
Si oui, essaie de mettre `TRAEFIK_PORT=80` dans le `.env` (puis `./scripts/docker.sh up -d`) et de te connecter à l'appli via 192.168.xxx.xxx sans le port

**Comment by mvergez** [comment]
> C'est vrai que dans notre cas, on a besoin d'utiliser GeoCam uniquement en local, pas forcément ouvert vers l'extérieur. Du coup, je ne vois pas comment activer le HTTPS si notre serveur n'a pas d'adresse publique !

Effectivement si vous êtes qu'en local ça ne vaut pas le coup d'exposer la machine, de prendre un nom de domaine, le lier à la machine et générer un certificat...

> Cela dit, on a eu des retours d'autres parcs qui eux souhaiteraient que leur GeoCam puisse être ouvert à l'extérieur afin que leurs correspondants "pièges photo" puissent saisir directement leur données dans l'interface.

Dans ce cas là ce sera possible, normalement assez facilement, comme on a fait pour la démo

**Comment by geobrun** [comment]
Merci @mvergez, il n'y a plus d'erreur de type CORS dans la console a priori !

Par contre, il y a toujours un souci d'erreur 500 lorsque j'envoie la requête suivante au clic sur "Enregistrer" :` POST http://192.168.0.62/api/v1/projects/`.

J'ai en plus ce message d'erreur qui apparaît pour le fichier `app/src/components/projectModale.tsx:65` : `Uncaught (in promise) TypeError: err.body.detail is undefined`

**Comment by mvergez** [comment]
Top ! Un problème de résolu !

Est-ce que tu aurais les logs de l'api : `./scripts/docker.sh logs api` ? Peut être que cela peut nous aider.
L'erreur provient vraiment de l'api je pense car le POST ne fonctionne pas...

**Comment by mvergez** [comment]
Ok je viens de tester chez moi et j'ai eu le même souci que toi, c'est bon signe :) 

Alors en fait l'erreur indique qu'il n'y a pas d'utilisateur dans la base de données. Ils ne sont pas créés par défaut car on a pas mis en place la gestion d'utilisateurs, mais ces derniers sont quand même prévus dans la base de données et associés au projet. 

Donc ! La solution la plus simple et d'initialiser la base de données avec des données d'exemple, quitte à faire le tri après. La commande est la suivante : `./scripts/docker.sh exec api python -c "from src.connectors.database import init_db; init_db()"` (comme indiqué ici https://github.com/NaturalSolutions/GeoCam#sample-data)

Elle permet d'exécuter une fonction python dans le conteneur de l'api pour initialiser la base de données avec des données d'exemples.

Je viens de tester, l'ajout de projet fonctionne après

**Comment by mvergez** [comment]
Merci pour tes retours en tout cas, il va falloir qu'on s'occupe de corriger ça :)

**Comment by geobrun** [comment]
Ok, ça a fonctionné, merci ! :)

Je laisse ma collègue tester la semaine prochaine pour voir s'il y a d'autres petits soucis (je serai en congés) et je faisun point avec elle en rentrant pour voir comment on avance sur le développement des fonctionnalités vidéo.

**Comment by geobrun** [comment]
Après test avec ma collègue, il ne reste a priori qu'un seul souci : les images ne se chargent pas dans le navigateur. Voilà un exemple de ce qu'on obtient :

![pb_image_geocam](https://github.com/NaturalSolutions/GeoCam/assets/68049696/b9e72a70-052a-4efd-97c5-acf389c09cc7)

J'ai pas mal de messages dans ce genre dans la console de débogage de Firefox :
```
Warning: validateDOMNesting(...): <hr> cannot appear as a descendant of <p>
p
div
ButtonStatus@http://192.168.0.62/static/js/bundle.js:4950:7
div
p
```

Problème encore avec l'adresse IP du serveur ?

**Comment by MathildeNS** [comment]
Nous n'avons pas réussi à reproduire le bug de notre côté. 

Pourriez-vous vérifier que l'image a bien été importée dans Minio : `http://nom_domain:9001` (vous trouverez vos identifiants dans votre fichier `.env` du dossier `docker`) dans le miniobucket ? Et si vous avez un accès à la BDD (via DBeaver par exemple) pourriez-vous vérifier que vous avez bien en BDD dans la table `file` une ligne correspondant à cette image et m'indiquer ce que contient la colonne `hash` ?

Pourriez-vous également inspecter l'image (clic droit à l'emplacement de l'image > inspecter), nous envoyer ce que contient la balise <img> et vérifier qu'en cliquant sur le lien src dans cette balise l'image se télécharge ?

**Comment by mvergez** [comment]
Pardon je n'ai pas répondu à l'issue.

Effectivement @MathildeNS, nous avions fait nos tests avec localhost ou en mode prod alors que @geobrun se connecte via une adresse IP ce qui crée tous les problèmes de cette issue et un problème avec minio.

Pour reproduire le problème, on pourrait éditer notre fichier `/etc/hosts` avec quelque chose comme : 

```
127.0.0.1       geocam.localdomain
```

Et renseigner `geocam.localdomain` dans le `.env` au lieu de localhost.

J'avais anticipé ce problème mais j'ai pas pris le temps de répondre à l'issue.

Tu as la bonne piste @MathildeNS, le lien est bon mais traeffik ne gère pas bien la redirection vers minio, il faut qu'il le fasse comme dans `docker-compose.prod.yml` ce qui donnerait quelque chose comme : 
```yaml
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=${TRAEFIK_ROUTER_RULE_MINIO-PathPrefix(`/miniobucket`)}
```
Qu'il faudrait rajouter juste en dessous de : https://github.com/NaturalSolutions/GeoCam/blob/85ac3c3c2bfdcb788535cb2a86371bf86919c5c8/docker/docker-compose.yml#L92-L102

Et dans le fichier .env, ajouter : 

```
TRAEFIK_ROUTER_RULE_MINIO=Host(`${DOMAIN}`) && PathPrefix(`/${MINIO_BUCKET_NAME}`)
```

Je pense que le problème vient de là.

Je prendrai le temps de faire une PR avec ces corrections dans les `docker-compose` et dans les `.env`

**Comment by geobrun** [comment]
Je vous remercie pour vos retours, je vais regarder tout ça vendredi !

**Comment by geobrun** [comment]
Merci à tous les deux, problème résolu avec les lignes indiquées par @mvergez ! :)

Je fais un point avec ma collègue en début de semaine pour la suite.

NB pour la rédaction de la future documentation : ne pas oublier de relancer la commande `./scripts/docker.sh up -d` après la modification du fichier `.env`.
